# ?????
server.port=9090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/t001?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=02017216

# ??????
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ????????QQ?????????
spring.mail.host=smtp.qq.com
spring.mail.username=201506520@qq.com
spring.mail.password=gfptrckbfzyubigi
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

# MyBatis??
mybatis.mapper-locations=classpath:mapper/*.xml
# ??MyBatis SQL??????????????
# mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis-Plus?????SQL???
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ????????
files.upload.path=D:\\code\\file\\
spring.profiles.active=knif4j
knife4j.enable=true

