## ?????
#server.port=8081
## ????
#spring.application.name=hmdp
## ????? - ?????????????????? ??
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## ??????? 2??? -> &allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&**nullCatalogMeansCurrent=true&allowMultiQueries=true**
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&allowMultiQueries=true&mysql80CompatibilityMode=truespring.datasource.username=root
#spring.datasource.password=02017216
## ?????????????????????????
##spring.datasource.hikari.maximum-pool-size=10
##spring.datasource.hikari.connection-timeout=30000
#
## Redis?? - ???????spring.data.redis ? spring.redis ?? ????
#spring.data.redis.host=192.168.44.171
#
#spring.data.redis.port=6379
#spring.data.redis.password=02017216
## Redis????? - ????+??????????????????? ??
##spring.redis.lettuce.pool.max-active=10
##spring.redis.lettuce.pool.max-idle=10
##spring.redis.lettuce.pool.min-idle=1
##spring.redis.lettuce.pool.time-between-eviction-runs=10s
#
## Jackson?? - ??JSON??null??????? ??
#spring.jackson.default-property-inclusion=non_null
#
## MyBatis-Plus?? - ??????????? ??
#mybatis-plus.type-aliases-package=com.hmdp.entity
#
## ???? - com.hmdp??debug??????? ??
#logging.level.com.hmdp=debug
# ????
server.port=8081
# ????
spring.application.name=hmdp

# ========== ????? - ????? ???? ==========
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# url????? &user=root&password=02017216  ???????????????????
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&allowMultiQueries=true&mysql80CompatibilityMode=true&user=root&password=02017216
# ???????????
spring.datasource.username=root
spring.datasource.password=02017216
# ????????????
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
# ?????Hikari???????????????
spring.datasource.hikari.username=root
spring.datasource.hikari.password=02017216

# ========== Redis?? - ???????????? ==========
spring.data.redis.host=192.168.44.101
spring.data.redis.port=6379
spring.data.redis.password=02017216
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=1
spring.data.redis.lettuce.pool.time-between-eviction-runs=10s

# Jackson??
spring.jackson.default-property-inclusion=non_null

# MyBatis-Plus??
mybatis-plus.type-aliases-package=com.hmdp.entity

# ????
logging.level.com.hmdp=debug